"""G代码生成器 - 支持车/铣/钻/镗/攻丝"""
from dataclasses import dataclass, field
from typing import List, Tuple
from enum import Enum
import math

class Operation(str, Enum):
    FACE_MILLING = "face_milling"      # 面铣
    PERIPHERAL_MILLING = "peripheral_milling"  # 轮廓铣
    POCKET_MILLING = "pocket_milling"  # 型腔铣
    DRILLING = "drilling"              # 钻孔
    DEEP_DRILL = "deep_drill"          # 深孔钻
    TAPPING = "tapping"                # 攻丝
    BORING = "boring"                  # 镗孔
    TURNING = "turning"                # 车削
    THREAD_TURNING = "thread_turning"  # 螺纹车削
    GROOVING = "grooving"              # 切槽

@dataclass
class Tool:
    type: str
    diameter: float
    flute_length: float = 0
    tool_number: int = 0
    comments: str = ""

@dataclass
class GCodeProgram:
    title: str = ""
    program_number: int = 1000
    tool_calls: List[str] = field(default_factory=list)
    moves: List[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)
    
    def to_string(self) -> str:
        lines = [f"O{self.program_number:04d} ({self.title})"]
        lines.append("; Generated by UG AI Auto-Programming")
        lines.append(f"; Program start: {self.metadata.get('start_time', 'N/A')}")
        for t in self.tool_calls:
            lines.append(t)
        lines.append("; === Main Program ===")
        lines.extend(self.moves)
        lines.append("; === End of Program ===")
        return "\n".join(lines) + "\n"

@dataclass
class Workpiece:
    name: str
    length: float
    width: float
    height: float
    x_origin: float = 0.0
    y_origin: float = 0.0
    z_origin: float = 0.0

def generate_gcode(
    operation: Operation,
    tool: Tool,
    workpiece: Workpiece,
    params: dict,
    holes: list = None,
    features: list = None
) -> GCodeProgram:
    """
    根据加工操作生成G代码
    
    Args:
        operation: 加工操作类型
        tool: 刀具信息
        workpiece: 工件信息
        params: 切削参数
            - spindle_speed: 主轴转速 RPM
            - feed_rate: 进给速度 mm/min
            - axial_depth: 轴向切深 mm
            - radial_depth: 径向切深 mm
            - cutting_speed: 切削速度 m/min
            - feed_per_tooth: 每齿进给 mm/z
        holes: 钻孔列表 [{"x":, "y":, "depth":, ...}]
        features: 特征列表
    
    Returns:
        GCodeProgram
    """
    prog = GCodeProgram(
        title=f"{operation.value}_{tool.type}_{tool.tool_number}",
        metadata={"start_time": params.get("start_time", "N/A")}
    )
    
    # 操作分发
    dispatch = {
        Operation.FACE_MILLING: _gen_face_milling,
        Operation.PERIPHERAL_MILLING: _gen_peripheral_milling,
        Operation.POCKET_MILLING: _gen_pocket_milling,
        Operation.DRILLING: _gen_drilling,
        Operation.DEEP_DRILL: _gen_deep_drill,
        Operation.TAPPING: _gen_tapping,
        Operation.BORING: _gen_boring,
        Operation.TURNING: _gen_turning,
        Operation.THREAD_TURNING: _gen_thread_turning,
        Operation.GROOVING: _gen_grooving,
    }
    
    gen_func = dispatch.get(operation)
    if gen_func:
        gen_func(prog, tool, workpiece, params, holes, features)
    else:
        prog.moves.append(f"; [WARN] 未实现的加工操作: {operation.value}")
    
    return prog

# ========== 各加工操作 G代码生成 ==========

def _gen_face_milling(prog, tool, wp, params, holes, features):
    """面铣 - 先生成安全高度移动，再分层下刀铣面"""
    # 刀具注释
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    prog.tool_calls.append(f"G94 G98")
    
    moves = prog.moves
    z_safe = wp.z_origin + 5.0
    z_start = wp.z_origin + 1.0
    axial = params['axial_depth']
    feed = params['feed_rate']
    
    # 定位到安全高度
    moves.append(f"G0 Z{z_safe:.3f}")
    moves.append(f"G0 X{wp.x_origin - 5:.3f} Y{wp.y_origin - 5:.3f}")
    moves.append(f"G1 Z{z_start:.3f} F{feed * 2:.0f}")
    
    # 分层铣面
    current_z = wp.z_origin
    depth_counter = 0
    while current_z > wp.z_origin - wp.height - 0.1:
        depth_counter += 1
        step_z = min(axial, current_z - wp.z_origin + wp.height)
        next_z = current_z - step_z
        
        moves.append(f"; === 第{depth_counter}层, Z={next_z:.3f} ===")
        moves.append(f"G0 Z{next_z + 1:.3f}")
        moves.append(f"G1 Z{next_z:.3f} F{feed * 0.5:.0f}")
        
        # 交叉铣削路径
        x = wp.x_origin - 5
        y = wp.y_origin - 5
        moves.append(f"G1 X{x:.3f} Y{y:.3f} F{feed:.0f}")
        
        y_end = wp.y_origin + wp.width + 5
        while y < y_end:
            moves.append(f"G1 Y{min(y + 10, y_end):.3f} F{feed:.0f}")
            y += 10
            moves.append(f"G1 Y{max(y - 10, wp.y_origin - 5):.3f} F{feed:.0f}")
            y -= 10
        
        x_end = wp.x_origin + wp.length + 5
        x = wp.x_origin - 5
        while x < x_end:
            moves.append(f"G1 X{min(x + 10, x_end):.3f} F{feed:.0f}")
            x += 10
            moves.append(f"G1 X{max(x - 10, wp.x_origin - 5):.3f} F{feed:.0f}")
            x -= 10
        
        current_z = next_z
    
    moves.append(f"G0 Z{z_safe:.3f}")
    moves.append("M5")

def _gen_peripheral_milling(prog, tool, wp, params, holes, features):
    """轮廓铣 - 沿工件外轮廓加工"""
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    prog.tool_calls.append(f"G94 G98")
    
    moves = prog.moves
    z_safe = wp.z_origin + 5.0
    axial = params['axial_depth']
    feed = params['feed_rate']
    
    cx = wp.x_origin + wp.length / 2
    cy = wp.y_origin + wp.width / 2
    half_w = wp.width / 2 + tool.diameter / 2
    half_l = wp.length / 2 + tool.diameter / 2
    
    moves.append(f"G0 Z{z_safe:.3f}")
    moves.append(f"G0 X{cx - half_l:.3f} Y{cy - half_w:.3f}")
    
    # 分层轮廓铣
    depth_counter = 0
    current_z = wp.z_origin
    while current_z > wp.z_origin - wp.height + 0.1:
        depth_counter += 1
        step_z = min(axial, current_z - wp.z_origin + wp.height)
        next_z = current_z - step_z
        
        moves.append(f"; === 轮廓层{depth_counter}, Z={next_z:.3f} ===")
        moves.append(f"G0 Z{next_z + 1:.3f}")
        moves.append(f"G1 Z{next_z:.3f} F{feed * 0.5:.0f}")
        
        # 矩形轮廓
        moves.append(f"G1 X{cx - half_l:.3f} F{feed:.0f}")
        moves.append(f"G1 Y{cy - half_w:.3f}")
        moves.append(f"G1 X{cx + half_l:.3f}")
        moves.append(f"G1 Y{cy + half_w:.3f}")
        moves.append(f"G1 X{cx - half_l:.3f}")
        moves.append(f"G1 Y{cy - half_w:.3f}")
        
        current_z = next_z
    
    moves.append(f"G0 Z{z_safe:.3f}")
    moves.append("M5")

def _gen_pocket_milling(prog, tool, wp, params, holes, features):
    """型腔铣 - 螺旋下刀 + 螺旋铣削"""
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    prog.tool_calls.append(f"G94 G98")
    
    moves = prog.moves
    z_safe = wp.z_origin + 5.0
    axial = params['axial_depth']
    feed = params['feed_rate']
    radial = params['radial_depth']
    
    cx = wp.x_origin + wp.length / 2
    cy = wp.y_origin + wp.width / 2
    
    moves.append(f"G0 Z{z_safe:.3f}")
    moves.append(f"G0 X{cx:.3f} Y{cy:.3f}")
    
    # 分层型腔铣
    depth_counter = 0
    current_z = wp.z_origin
    while current_z > wp.z_origin - wp.height + 0.1:
        depth_counter += 1
        step_z = min(axial, current_z - wp.z_origin + wp.height)
        next_z = current_z - step_z
        
        moves.append(f"; === 型腔层{depth_counter}, Z={next_z:.3f} ===")
        
        # 螺旋下刀
        spiral_start = next_z + axial
        spiral_z = current_z
        while spiral_z > next_z:
            z_step = min(axial / 3, spiral_z - next_z)
            spiral_z -= z_step
            r = (wp.width / 2 - radial)
            moves.append(f"G1 Z{spiral_z:.3f} F{feed * 0.3:.0f}")
            moves.append(f"G1 X{cx + r:.3f} Y{cy:.3f} F{feed:.0f}")
        
        # 螺旋铣削路径
        r = wp.width / 2 - radial
        num_circles = int(wp.length / (2 * radial)) + 1
        for i in range(num_circles):
            r_current = (i + 1) * radial
            if r_current > wp.width / 2: break
            moves.append(f"G1 X{cx + r_current:.3f} Y{cy:.3f} F{feed:.0f}")
            moves.append(f"G1 X{cx:.3f} Y{cy + r_current:.3f}")
            moves.append(f"G1 X{cx - r_current:.3f} Y{cy:.3f}")
            moves.append(f"G1 X{cx:.3f} Y{cy - r_current:.3f}")
    
    moves.append(f"G0 Z{z_safe:.3f}")
    moves.append("M5")

def _gen_drilling(prog, tool, wp, params, holes, features):
    """钻孔 - G81/G83 固定循环"""
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    prog.tool_calls.append(f"G94 G98")
    
    moves = prog.moves
    z_safe = wp.z_origin + 5.0
    z_r = wp.z_origin + 2.0  # 参考平面
    feed = params['feed_rate']
    
    if holes:
        for i, h in enumerate(holes, 1):
            hx, hy, hdepth = h.get("x", 0), h.get("y", 0), h.get("depth", 5)
            moves.append(f"; === 孔{i}: X={hx:.3f} Y={hy:.3f} D={hdepth:.3f} ===")
            moves.append(f"G0 Z{z_safe:.3f}")
            moves.append(f"G0 X{hx:.3f} Y{hy:.3f}")
            
            # 根据深度选择钻孔方式
            if hdepth > 3 * tool.diameter:
                # 深孔啄钻 G83
                depth = 0
                peck = min(2 * tool.diameter, hdepth / 3)
                while depth < hdepth:
                    depth = min(depth + peck, hdepth)
                    moves.append(f"G83 Z{wp.z_origin - depth:.3f} R{z_r:.3f} Q{int(peck * 1000):.0f} F{feed:.0f}")
                moves.append("G80")
            else:
                # 普通钻孔 G81
                moves.append(f"G81 Z{wp.z_origin - hdepth:.3f} R{z_r:.3f} F{feed:.0f}")
                moves.append("G80")
    
    moves.append("M5")

def _gen_deep_drill(prog, tool, wp, params, holes, features):
    """深孔钻 - G83 啄钻"""
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    prog.tool_calls.append(f"G94 G98")
    
    moves = prog.moves
    z_safe = wp.z_origin + 5.0
    z_r = wp.z_origin + 2.0
    feed = params['feed_rate']
    
    if holes:
        for i, h in enumerate(holes, 1):
            hx, hy, hdepth = h.get("x", 0), h.get("y", 0), h.get("depth", 20)
            moves.append(f"; === 深孔{i}: X={hx:.3f} Y={hy:.3f} D={hdepth:.3f} ===")
            moves.append(f"G0 Z{z_safe:.3f}")
            moves.append(f"G0 X{hx:.3f} Y{hy:.3f}")
            
            depth = 0
            peck = min(2 * tool.diameter, hdepth / 4)
            while depth < hdepth:
                depth = min(depth + peck, hdepth)
                moves.append(f"G83 Z{wp.z_origin - depth:.3f} R{z_r:.3f} Q{int(peck * 1000):.0f} F{feed:.0f}")
            moves.append("G80")
    
    moves.append("M5")

def _gen_tapping(prog, tool, tool_diam, wp, params, holes, features):
    """攻丝 - G84 右旋攻丝"""
    tool_diameter = tool_diam
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    prog.tool_calls.append(f"G94 G95")  # 每转进给
    
    moves = prog.moves
    z_safe = wp.z_origin + 5.0
    z_r = wp.z_origin + 2.0
    pitch = tool_diameter * 0.075 if tool_diameter < 12 else tool_diameter * 0.0625
    
    if holes:
        for i, h in enumerate(holes, 1):
            hx, hy, hdepth = h.get("x", 0), h.get("y", 0), h.get("depth", 10)
            moves.append(f"; === 攻丝{i}: X={hx:.3f} Y={hy:.3f} 螺距={pitch:.3f} ===")
            moves.append(f"G0 Z{z_safe:.3f}")
            moves.append(f"G0 X{hx:.3f} Y{hy:.3f}")
            moves.append(f"G84 Z{wp.z_origin - hdepth:.3f} R{z_r:.3f} F{pitch:.3f}")
            moves.append("G80")
    
    moves.append("M5")

def _gen_boring(prog, tool, wp, params, holes, features):
    """镗孔 - G76 精镗"""
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    prog.tool_calls.append(f"G94 G95")
    
    moves = prog.moves
    z_safe = wp.z_origin + 5.0
    z_r = wp.z_origin + 2.0
    
    if holes:
        for i, h in enumerate(holes, 1):
            hx, hy, hdepth = h.get("x", 0), h.get("y", 0), h.get("depth", 15)
            moves.append(f"; === 镗孔{i}: X={hx:.3f} Y={hy:.3f} ===")
            moves.append(f"G0 Z{z_safe:.3f}")
            moves.append(f"G0 X{hx:.3f} Y{hy:.3f}")
            moves.append(f"G76 Z{wp.z_origin - hdepth:.3f} R{z_r:.3f} Q{int(tool.diameter * 100):.0f} F{params['feed_rate']:.0f}")
            moves.append("G80")
    
    moves.append("M5")

def _gen_turning(prog, tool, wp, params, holes, features):
    """车削 - 外圆车削"""
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    prog.tool_calls.append(f"G97")
    
    moves = prog.moves
    feed = params['feed_rate']
    radial = params['radial_depth']
    
    # 端面加工
    moves.append(f"G0 X0 Z5.0")
    moves.append(f"G1 X{wp.height:.3f} F{feed:.0f}")
    moves.append(f"G0 X0 Z5.0")
    
    # 外圆车削
    current_d = wp.height
    end_d = 10.0
    while current_d > end_d:
        current_d = max(current_d - radial, end_d)
        moves.append(f"G0 X{current_d:.3f} Z5.0")
        moves.append(f"G1 Z0 F{feed:.0f}")
        moves.append(f"G1 Z{wp.length:.3f} F{feed:.0f}")
        moves.append(f"G1 X{current_d - radial:.3f}")
    
    moves.append("M5")

def _gen_thread_turning(prog, tool, tool_diam, wp, params, holes, features):
    """螺纹车削"""
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    prog.tool_calls.append(f"G96 S120")  # 恒线速
    
    moves = prog.moves
    pitch = tool_diam * 0.075
    num_threads = int(wp.height / (3.5 * pitch))
    
    moves.append(f"G0 X{wp.height + 5:.3f} Z5.0")
    moves.append(f"G32 Z-{wp.length:.3f} F{pitch:.3f}")
    moves.append(f"G0 X{wp.height + 5:.3f} Z5.0")
    
    for i in range(num_threads):
        depth = 0.5 * pitch * (1 - (i + 1) / (num_threads + 1)) ** 2
        moves.append(f"G0 X{wp.height - 2 * depth:.3f}")
        moves.append(f"G32 Z-{wp.length:.3f} F{pitch:.3f}")
        moves.append(f"G0 X{wp.height + 5:.3f} Z5.0")
    
    moves.append("M5")

def _gen_grooving(prog, tool, wp, params, holes, features):
    """切槽"""
    prog.tool_calls.append(f"T{tool.tool_number} M6 ({tool.type} D={tool.diameter})")
    prog.tool_calls.append(f"M3 S{int(params['spindle_speed'])}")
    
    moves = prog.moves
    feed = params['feed_rate']
    
    # 根据特征或holes定位槽
    if features:
        for i, f in enumerate(features, 1):
            gx, gw = f.get("x", 0), f.get("width", 2)
            moves.append(f"; === 槽{i}: X={gx:.3f} W={gw:.3f} ===")
            moves.append(f"G0 X{gx + gw / 2:.3f} Z{wp.length + 5:.3f}")
            moves.append(f"G1 Z{wp.z_origin - 10:.3f} F{feed * 0.3:.0f}")
            moves.append(f"G1 X{gx - gw / 2:.3f} F{feed * 0.5:.0f}")
            moves.append(f"G1 X{gx + gw / 2:.3f}")
            moves.append(f"G0 Z{wp.length + 5:.3f}")
    else:
        moves.append(f"G0 X{tool.diameter} Z5.0")
        moves.append(f"G1 Z-10 F{feed * 0.3:.0f}")
        moves.append(f"G0 Z{wp.length + 5:.3f}")
    
    moves.append("M5")
