"""后处理器 - 生成 FANUC / SIEMENS / 广数 格式G代码"""
from typing import List
from enum import Enum

class PostProcessor(str, Enum):
    FANUC = "FANUC"
    SIEMENS = "SIEMENS"
    GSK = "广数"

def apply_postproc(gcode_content: str, post_type: PostProcessor) -> str:
    """
    将通用G代码转换为指定系统格式
    
    Args:
        gcode_content: 通用G代码字符串
        post_type: 后处理类型
    
    Returns:
        转换后的G代码字符串
    """
    lines = gcode_content.split("\n")
    result = []
    
    for line in lines:
        stripped = line.strip()
        
        # 注释行原样保留
        if stripped.startswith(";") or stripped == "":
            result.append(line)
            continue
        
        # 处理 M 代码（不同系统的差异）
        if stripped.startswith("M"):
            stripped = _transform_m_code(stripped, post_type)
        
        # 处理 S 代码（主轴速度指令差异）
        if stripped.startswith("S") and "G96" in stripped:
            if post_type == PostProcessor.FANUC:
                stripped = stripped.replace("G96", "G96")
            elif post_type == PostProcessor.GSK:
                stripped = stripped.replace("G96", "G96")
        
        # 处理 G 代码指令
        stripped = _transform_g_codes(stripped, post_type)
        
        result.append(stripped)
    
    return "\n".join(result)

def _transform_m_code(line: str, post: PostProcessor) -> str:
    """不同系统 M 代码差异处理"""
    parts = line.split()
    result = []
    
    for part in parts:
        if part.startswith("M"):
            if post == PostProcessor.SIEMENS:
                # SIEMENS 的 M 代码格式略有不同
                if part == "M3":
                    result.append("M3")  # SIEMENS 也支持 M3
                elif part == "M5":
                    result.append("M5")
                elif part == "M6":
                    result.append("T=" + part[1:])  # SIEMENS: T=6
            else:
                result.append(part)
        else:
            result.append(part)
    
    return " ".join(result)

def _transform_g_codes(line: str, post: PostProcessor) -> str:
    """不同系统 G 代码差异处理"""
    parts = line.split()
    result = []
    
    for part in parts:
        if part.startswith("G"):
            if post == PostProcessor.SIEMENS:
                # SIEMENS 对某些 G 代码使用不同编号
                pass  # SIEMENS 大多数 G 代码兼容
            # GSK 基本兼容 FANUC
        result.append(part)
    
    return " ".join(result)

def generate_post_header(post_type: PostProcessor, title: str = "Auto Program") -> str:
    """生成各系统专用头部"""
    headers = {
        PostProcessor.FANUC: f"; FANUC CNC System\n; Program: {title}\n; Generated by UG AI Auto-Programming",
        PostProcessor.SIEMENS: f"; SIEMENS SINUMERIK System\n; Program: {title}\n; Generated by UG AI Auto-Programming",
        PostProcessor.GSK: f"; 广数 CNC 系统\n; 程序: {title}\n; 由 UG AI 自动编程生成",
    }
    return headers.get(post_type, headers[PostProcessor.FANUC])
